import { SemesterRecord } from "@/lib/semesters/actions";
import { SubjectWithStats } from "@/lib/subjects/actions";
import { AttendanceHistoryItem } from "@/lib/attendance/actions";
import { TimetableEntry } from "@/lib/timetable/actions";
import { GradeRecord } from "@/lib/grades/actions";
import { NotificationRecord } from "@/lib/notifications/actions";

export const DEMO_SEMESTERS: SemesterRecord[] = [
  {
    id: "sem-1",
    user_id: "demo-user",
    name: "Spring 2026",
    academic_year: "2025-2026",
    is_active: true,
    target_attendance: 75,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "sem-2",
    user_id: "demo-user",
    name: "Fall 2025",
    academic_year: "2025-2026",
    is_active: false,
    target_attendance: 75,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_SUBJECTS: SubjectWithStats[] = [
  {
    id: "sub-1",
    user_id: "demo-user",
    semester_id: "sem-1",
    name: "Operating Systems",
    code: "CS301",
    teacher: "Dr. Alan Turing",
    credits: 4,
    minimum_attendance: 75,
    color: "#3b82f6",
    archived: false,
    total_classes: 30,
    attended_classes: 25,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "sub-2",
    user_id: "demo-user",
    semester_id: "sem-1",
    name: "Database Management Systems",
    code: "CS302",
    teacher: "Prof. Edgar Codd",
    credits: 4,
    minimum_attendance: 75,
    color: "#10b981",
    archived: false,
    total_classes: 28,
    attended_classes: 24,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "sub-3",
    user_id: "demo-user",
    semester_id: "sem-1",
    name: "Computer Networks",
    code: "CS303",
    teacher: "Dr. Vint Cerf",
    credits: 3,
    minimum_attendance: 75,
    color: "#f59e0b",
    archived: false,
    total_classes: 30,
    attended_classes: 21,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "sub-4",
    user_id: "demo-user",
    semester_id: "sem-1",
    name: "Software Engineering Lab",
    code: "CS304L",
    teacher: "Prof. Grace Hopper",
    credits: 2,
    minimum_attendance: 80,
    color: "#8b5cf6",
    archived: false,
    total_classes: 20,
    attended_classes: 19,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_HISTORY: AttendanceHistoryItem[] = [
  {
    id: "att-1",
    date: "2026-03-01",
    status: "present",
    notes: "Kernel Architecture and Process Scheduling",
    created_at: "2026-03-01T09:30:00Z",
    subjects: { id: "sub-1", name: "Operating Systems", code: "CS301", color: "#3b82f6" },
  },
  {
    id: "att-2",
    date: "2026-03-01",
    status: "present",
    notes: "SQL Query Optimization and Indexing",
    created_at: "2026-03-01T11:30:00Z",
    subjects: { id: "sub-2", name: "Database Management Systems", code: "CS302", color: "#10b981" },
  },
  {
    id: "att-3",
    date: "2026-03-02",
    status: "absent",
    notes: "TCP Handshake and Congestion Control",
    created_at: "2026-03-02T10:30:00Z",
    subjects: { id: "sub-3", name: "Computer Networks", code: "CS303", color: "#f59e0b" },
  },
  {
    id: "att-4",
    date: "2026-03-03",
    status: "present",
    notes: "Unit Testing & CI/CD Pipelines Lab",
    created_at: "2026-03-03T14:30:00Z",
    subjects: { id: "sub-4", name: "Software Engineering Lab", code: "CS304L", color: "#8b5cf6" },
  },
];

export const DEMO_TIMETABLE: TimetableEntry[] = [
  // Monday (1)
  {
    id: "time-1",
    user_id: "demo-user",
    subject_id: "sub-1",
    day_of_week: 1,
    start_time: "09:00:00",
    end_time: "10:30:00",
    room: "Auditorium 2B",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-1", name: "Operating Systems", code: "CS301", color: "#3b82f6", teacher: "Dr. Alan Turing" },
  },
  {
    id: "time-2",
    user_id: "demo-user",
    subject_id: "sub-2",
    day_of_week: 1,
    start_time: "11:00:00",
    end_time: "12:30:00",
    room: "CS Lab 3",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-2", name: "Database Management Systems", code: "CS302", color: "#10b981", teacher: "Prof. Edgar Codd" },
  },
  // Tuesday (2)
  {
    id: "time-3",
    user_id: "demo-user",
    subject_id: "sub-3",
    day_of_week: 2,
    start_time: "10:00:00",
    end_time: "11:30:00",
    room: "Room 404",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-3", name: "Computer Networks", code: "CS303", color: "#f59e0b", teacher: "Dr. Vint Cerf" },
  },
  {
    id: "time-4",
    user_id: "demo-user",
    subject_id: "sub-1",
    day_of_week: 2,
    start_time: "14:00:00",
    end_time: "15:30:00",
    room: "Auditorium 2B",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-1", name: "Operating Systems", code: "CS301", color: "#3b82f6", teacher: "Dr. Alan Turing" },
  },
  // Wednesday (3)
  {
    id: "time-5",
    user_id: "demo-user",
    subject_id: "sub-4",
    day_of_week: 3,
    start_time: "14:00:00",
    end_time: "16:00:00",
    room: "Software Lab 1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-4", name: "Software Engineering Lab", code: "CS304L", color: "#8b5cf6", teacher: "Prof. Grace Hopper" },
  },
  // Thursday (4)
  {
    id: "time-6",
    user_id: "demo-user",
    subject_id: "sub-2",
    day_of_week: 4,
    start_time: "09:30:00",
    end_time: "11:00:00",
    room: "CS Lab 3",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-2", name: "Database Management Systems", code: "CS302", color: "#10b981", teacher: "Prof. Edgar Codd" },
  },
  {
    id: "time-7",
    user_id: "demo-user",
    subject_id: "sub-3",
    day_of_week: 4,
    start_time: "11:30:00",
    end_time: "13:00:00",
    room: "Room 404",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-3", name: "Computer Networks", code: "CS303", color: "#f59e0b", teacher: "Dr. Vint Cerf" },
  },
  // Friday (5)
  {
    id: "time-8",
    user_id: "demo-user",
    subject_id: "sub-1",
    day_of_week: 5,
    start_time: "10:00:00",
    end_time: "11:30:00",
    room: "Auditorium 2B",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-1", name: "Operating Systems", code: "CS301", color: "#3b82f6", teacher: "Dr. Alan Turing" },
  },
  {
    id: "time-9",
    user_id: "demo-user",
    subject_id: "sub-4",
    day_of_week: 5,
    start_time: "13:00:00",
    end_time: "15:00:00",
    room: "Software Lab 1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-4", name: "Software Engineering Lab", code: "CS304L", color: "#8b5cf6", teacher: "Prof. Grace Hopper" },
  },
  // Saturday (6)
  {
    id: "time-10",
    user_id: "demo-user",
    subject_id: "sub-2",
    day_of_week: 6,
    start_time: "09:00:00",
    end_time: "10:30:00",
    room: "CS Lab 3",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-2", name: "Database Management Systems", code: "CS302", color: "#10b981", teacher: "Prof. Edgar Codd" },
  },
  {
    id: "time-11",
    user_id: "demo-user",
    subject_id: "sub-3",
    day_of_week: 6,
    start_time: "11:00:00",
    end_time: "12:30:00",
    room: "Room 404",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-3", name: "Computer Networks", code: "CS303", color: "#f59e0b", teacher: "Dr. Vint Cerf" },
  },
  // Sunday (0) - Weekend Special Session
  {
    id: "time-12",
    user_id: "demo-user",
    subject_id: "sub-4",
    day_of_week: 0,
    start_time: "10:00:00",
    end_time: "12:00:00",
    room: "Software Lab 1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-4", name: "Software Engineering Lab", code: "CS304L", color: "#8b5cf6", teacher: "Prof. Grace Hopper" },
  },
];

export const DEMO_GRADES: GradeRecord[] = [
  {
    id: "gr-1",
    user_id: "demo-user",
    subject_id: "sub-1",
    credits: 4,
    grade: "A",
    grade_scale: "4.0",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-1", name: "Operating Systems", code: "CS301", color: "#3b82f6" },
  },
  {
    id: "gr-2",
    user_id: "demo-user",
    subject_id: "sub-2",
    credits: 4,
    grade: "A",
    grade_scale: "4.0",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    subjects: { id: "sub-2", name: "Database Management Systems", code: "CS302", color: "#10b981" },
  },
];

export const DEMO_NOTIFICATIONS: NotificationRecord[] = [
  {
    id: "notif-1",
    user_id: "demo-user",
    title: "Critical Attendance Warning: Computer Networks",
    message: "Your attendance in Computer Networks is at 70.0%, which is below the mandatory 75.0% threshold. You must attend the next 2 classes to avoid debarment.",
    type: "attendance_below_minimum",
    read: false,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "notif-2",
    user_id: "demo-user",
    title: "Safe Bunk Alert: Software Engineering Lab",
    message: "You have maintained 95.0% attendance. You have 4 safe leaves remaining for this course without dropping below 80%.",
    type: "recovery_warning",
    read: false,
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
];